name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #国际化
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.0 #toast
  dio: 2.1.13 #网络请求
  http: ^0.12.0
  flutter_webview_plugin: ^0.3.5 #Webview
  flutter_easyrefresh: ^2.0.2 #列表下拉刷新和上拉加载更多
  flutter_swiper: ^1.1.6 #banner
  url_launcher: ^5.1.2 #支持打开网络，电话，短信和电子邮件。
  path_provider: ^1.2.0 #文件读写
  image_picker: ^0.6.1+2 #调系统相册选图
  #multi_image_picker: ^4.5.0 #多图选择
  cached_network_image: ^1.1.1 #图片加载缓存
  package_info: ^0.4.0+6 #用于获取应用程序的信息
  device_info: ^0.4.0+2 #用于获取手机设备的信息
  photo_view: ^0.4.2 #图片预览
  image_cropper: ^1.0.2 #图片裁剪
  flutter_screenutil: ^0.5.3 #屏幕适配
  barcode_scan: ^1.0.0 # 扫描二维码
  qr_flutter: ^2.1.0+55 #二维码生成
  percent_indicator: ^2.1.1 #进度条
  shared_preferences: ^0.5.3+4 #数据缓存
  camera: ^0.5.3+1 #相机
  flutter_svg: ^0.14.0 #加载SVG图片
  flutter_spinkit: "^3.1.0" #用于各种加载中的样式
  lpinyin: ^1.0.7 #汉字转拼音
  azlistview: ^0.1.2
  fancy_bottom_navigation: ^0.3.2
  sensors: ^0.4.0+1
  connectivity: ^0.4.3+1 #检查网络连接状态
  video_player: ^0.10.1+6
  flutter_local_notifications: ^0.8.1+1
  intl: 0.15.8 #

  #Fluro is a Flutter routing library that adds flexible routing options like wildcards,
  #named parameters and clear route definitions.
  fluro: "^1.4.0" #路由

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - assets/images/image01.png
    - assets/images/image02.png
    - assets/images/ic_account.svg
    - assets/data/china.json